### ISSUE TITLE
Inquiry about Soil Data Transformation

### ISSUE THREAD

**Issue by karimmamer** [soilspectroscopy/ossl-manual#14]
Hi,

I am confused about the transformation applied to the nitrogen content ("n.tot_usda.a623_w.pc") in level 1 data downloaded from [here](https://storage.googleapis.com/soilspec4gg-public/ossl_all_L1_v1.2.csv.gz). 

In the training code, log1p is applied to the variable while in the description log2 is written in the dataset sources figure.

Would appreciate clarifying the final transformation applied to it and other soil data as well.

Thanks

**Comment by zecojls** [comment]
Hi @karimmamer,

Sorry for the confusion. The data is provided in original units in the database and CSV files. However, I applied a log2 in the description legend plots to make the count visualization better. I will amend this to avoid more confusion.

For the models, yes, all of them are trained in log1p units and the goodness-of-fit metrics (RMSE and bias) and accuracy plots are displayed in this scale. However, if you get your predictions using the Engine, the results are already back-transformed to the original scale, in this case, wt% for total N.

Cheers

**Comment by karimmamer** [comment]
Thanks a lot @zecojls for your reply. I understand now.

Another question if you may, how to convert "n.tot_usda.a623_w.pc" to mg/kg?

**Comment by zecojls** [comment]
Be aware this is total Nitrogen. From [Research Gate](https://www.researchgate.net/post/Is_it_possible_to_convert_soil_nutrient_concentrations_TN_TC_etc_represented_as_a_percent_to_a_mass_mass_concentration_ie_mg_kg):
"Soil test reports generally express TN and TC as a percent (%) of dry mass. As an example, if the report says soil contains 1.23% of TN, this means that there is 1.23 grams of TN in 100 grams of dry soil.
To convert TN or TC expressed in % to g/kg dry soil:
1.23% TN = (1.23/100) x 1000 = 12.3 g/kg dry soil"

**Comment by karimmamer** [comment]
Thanks a lot José. Appreciate your help.
