### ISSUE TITLE
Registered spectral library edits (section 3.2)

### ISSUE THREAD

**Issue by jsanderman** [soilspectroscopy/ossl-manual#3]
For KSSL, please revise "Currently not available publicly for use." to "Freely available by request."

For AFSIS1 the location and scan numbers have been copied from LUCAS, the number of scans (with lab data) is 1903, not sure how many unique locations.

**Comment by thengl** [comment]
Now fixed see: https://soilspectroscopy.github.io/ossl-manual/#acknowledgments
