### ISSUE TITLE
Unable to access database

### ISSUE THREAD

**Issue by L-u-d-0-v-i-c** [soilspectroscopy/ossl-manual#6]
Hello!

I've tried to connect to the mongoDB database of OSSL using Studio 3T, MongoDB Compass or even pymongo. It seems that I can connect to the DB but it seems empty. So, I probably did something wrong.

I tried to connect with MongoDB Compass using the following URI:
mongodb://soilspec4gg:soilspec4gg@api.soilspectroscopy.org:27017/?ssl=true&authSource=soilspec4gg

Host: api.soilspectroscopy.org:27017
Username: soilspec4gg
Password: soilspec4gg
Authentification Database: soilspec4gg
With SSL/TLS Connection On.

I don't have errors with these parameters, but in the Database tab, it says it's empty.
Could you help me with that?

Thanks.

**Comment by zecojls** [comment]
Hi @L-u-d-0-v-i-c ,

We have been updating the database and access options in the past months, so please check if you are now able to access the OSSL through MongoDB. We have improved the example in the manual using R:
https://soilspectroscopy.github.io/ossl-manual/ossl-database-access.html#mongodb
