### ISSUE TITLE
[which-repo?] opusreader2 as spectro IO tool

### ISSUE THREAD

**Issue by philipp-baumann** [soilspectroscopy/ossl-manual#9]
Hi @zecojls 
I vaguely remember I read something about R tools in spectroscopy, not sure if it was here in the manual or elsewhere.
Just wanted to make you aware that we at spectral-cockpit team have a reader in R for Bruker binary files. It is almost CRAN ready, and could be added as a resource. You find more details in the repo here:
https://github.com/spectral-cockpit/opusreader2
It is zero dependency besides base R and quite production ready (new stuff like time-resolved spectra is in progress, but the core API is now stable). 
Cheers,
Philipp

**Comment by zecojls** [comment]
Hi @philipp-baumann,

We have a section in the OSSL manual called [Soil spectroscopy tools and users](https://soilspectroscopy.github.io/ossl-manual/soil-spectroscopy-tools-and-users.html). Under it, we provided a list of software (basically R packages) including opusreader2 and other packages: [Soil Spectroscopy software](https://soilspectroscopy.github.io/ossl-manual/soil-spectroscopy-tools-and-users.html#soil-spectroscopy-software).

Well, it looked like we have listed `opusreader2` but I made a mistake with the `asdreader` and `opusreader2` description. Now it should be fixed.

By the way, we really appreciate your work on opusreader2, it works great and we have been using it a lot in our pipeline. It is nice to see that you refactored the previous version with zero-dependency or just using base R. Thank you.

**Comment by philipp-baumann** [comment]
> Hi @philipp-baumann,
> 
> We have a section in the OSSL manual called [Soil spectroscopy tools and users](https://soilspectroscopy.github.io/ossl-manual/soil-spectroscopy-tools-and-users.html). Under it, we provided a list of software (basically R packages) including opusreader2 and other packages: [Soil Spectroscopy software](https://soilspectroscopy.github.io/ossl-manual/soil-spectroscopy-tools-and-users.html#soil-spectroscopy-software).
> 
> Well, it looked like we have listed `opusreader2` but I made a mistake with the `asdreader` and `opusreader2` description. Now it should be fixed.
> 
> By the way, we really appreciate your work on opusreader2, it works great and we have been using it a lot in our pipeline. It is nice to see that you refactored the previous version with zero-dependency or just using base R. Thank you.

just one minor 🙃 we're currently at v0.2.0
